### ISSUE TITLE
Intel GM45 GPU blacks out (sometimes hangs) with PC-BSD 11.0-CURRENT

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/freebsd-base-graphics#9]
Spun off from [Intel GM45 GPU hangs, PC-BSD 11.0-CURRENT, sysctl hw.dri.0.info.i915_error_state](https://lists.freebsd.org/pipermail/freebsd-x11/2016-February/017259.html) following discussion in IRC. 

December, January and February distributions of CURRENT are very prone to blackouts with [an Ergo Vista 621](https://forums.pcbsd.org/thread-20235.html) notebook. 

Maybe easiest to reproduce by launching GNOME System Monitor; for me a blackout occurs almost immediately, or within a few seconds.

**Comment by grahamperrin** [comment]
```
$ freebsd-version ; uname -a
11.0-CURRENTFEB2016
FreeBSD cces3-gjp4-pc-bsd-ergovista621.university.brighton.ac.uk 11.0-CURRENTFEB2016 FreeBSD 11.0-CURRENTFEB2016 #5 cbe5270(freebsd-base-graphics): Mon Feb  1 00:17:40 UTC 2016     root@devastator:/usr/obj/net/executor/builds/git/freebsd-11-graphics/sys/GENERIC  amd64
```

[messages.txt](https://github.com/freebsd/freebsd-base-graphics/files/148636/messages.txt)

**Comment by grahamperrin** [comment]
PC-BSD 11.0-CURRENTNOV2015 is trouble-free; no blackouts.

```
$ freebsd-version ; uname -a ; cat /usr/local/etc/pkg/repos/pcbsd.conf | grep -i url
11.0-CURRENTNOV2015
FreeBSD cces3-gjp4-pc-bsd-ergovista621.university.brighton.ac.uk 11.0-CURRENTNOV2015 FreeBSD 11.0-CURRENTNOV2015 #0 54248db(freebsd-base-graphics)-dirty: Mon Oct 26 17:00:21 UTC 2015     root@devastator:/usr/obj/net/executor/builds/git/freebsd-11-graphics/sys/GENERIC  amd64
               url: "http://pkg.cdn.pcbsd.org/11.0-CURRENTFEB2016/edge/amd64",
$ 
```
[messages.txt](https://github.com/freebsd/freebsd-base-graphics/files/149171/messages.txt)

**Comment by grahamperrin** [comment]
Notes from two hangs whilst using SCFB. 

[2016-03-02 13-30-08.txt](https://github.com/freebsd/freebsd-base-graphics/files/155058/2016-03-02.13-30-08.txt)

[2016-03-02 14-01-15.txt](https://github.com/freebsd/freebsd-base-graphics/files/155059/2016-03-02.14-01-15.txt)

**Comment by grahamperrin** [comment]
A hang whilst using intel-3d-enable. 

[2016-03-02 14-23.txt](https://github.com/freebsd/freebsd-base-graphics/files/155061/2016-03-02.14-23.txt)

[error_state.txt](https://github.com/freebsd/freebsd-base-graphics/files/155062/error_state.txt)

**Comment by grahamperrin** [comment]
First use of PC-BSD 11.0-CURRENTMAR2013 with intel-3d-enable: 

 - uptime of 2 hours, 30 minutes – probably more than two hours logged in (probably to Lumina) – without a blackout

I ran a variety of apps concurrently, but not enough to use swap. 

I'd like to test more thoroughly. In the meantime I wonder whether 11.0-CURRENTMAR2013 includes a fix for the issue.

**Comment by dumbbell** [comment]
That's good news! Your blackout was probably a consequence of the two bugs I had in `__wait_seqno()`.

Here, I was unable to reproduce it.

**Comment by grahamperrin** [comment]
I had just one blackout a few weeks ago, probably with KDE Plasma 4 on PC-BSD 11.0-CURRENTMAY2016. I didn't have time to gather information; I'm happy to treat that one incident as negligible, maybe with a cause unrelated to earlier incidents.
